### ISSUE TITLE
raspi-config appends to the end of config.txt

### ISSUE THREAD

**Issue by parkerlreed** [asb/raspi-config#31]
This is all fine and dandy unless you don't see the bottom, only see the top commented lines and uncomment and edit those as needed. I was confused as to why the options I was setting at the top were not taking effect.

http://hastebin.com/qusohupupu.vala

**Comment by Ruffio** [comment]
@parkerlreed is this still an issue? If not, please close this issue or create a new issue at the NOOBS repository. Thanks.

**Comment by parkerlreed** [comment]
Oh dear lord. I don't even have a Pi anymore. I guess I'll just close.
