### ISSUE TITLE
Make compatible with Raspberry Pi Zero

### ISSUE THREAD

**Issue by incyi** [asb/raspi-config#56]
Some of the settings are not usefull for the Raspberry Pi Zero. Please let's make this fully compatible with the Raspberry Pi Zero.

I can check to the code if this is OK.

**Comment by lurch** [comment]
See https://github.com/RPi-Distro/raspi-config/issues/11#issuecomment-174213193

So I guess any usability issues you have should be filed against the GUI tool at https://github.com/raspberrypi/rc_gui/issues
