### ISSUE TITLE
Add a OpenGLES functionality warning to the OpenGL page

### ISSUE THREAD

**Issue by WayneKeenan** [asb/raspi-config#61]
Hi,

Enabling the OpenGL desktop acceleration support stops OpenGLES based apps from working; this is currently the expected behaviour: https://github.com/raspberrypi/firmware/issues/556

As this will effect a number of OpenGL ES based applications and libraries (including the bundled VideoCore examples under /opt/vc) already in the wild, please could you add a warning on the settings page along the lines of:

"WARNING: Enabling this option disables OpenGL ES for both console only and desktop applications."

Thank you and all the best
Wayne

**Comment by TheBubbleWorks** [comment]
closing, dormant repo.

**Comment by lurch** [comment]
This issue got re-filed (and then closed) at https://github.com/RPi-Distro/raspi-config/issues/21 so it should be closed here, since this repo is (AFAIK) now defunct.
